Algoritmo "cigarro"

Var

numaco, time, cigdia:real
valmaco, valorf:real

Inicio

escreval("Quantos cigarros sao comprados em um dia?")
leia(cigdia)

escreval("Qual o preco do maco de cigarro?")
leia(valmaco)

escreval("Por quanto tempo voce fumou?(em anos)")
leia(time)

valorf <- (((cigdia/20)* 365 * valmaco) * time)))

escreval("Voce gastou ", valorf, " reais com cigarro durante sua vida")

Fimalgoritmo