Algoritmo "inverter"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2022
Var

a, b, c:real

Inicio

escreval("Qual o valor de A?")
leia(a)

escreval("Qual o valor de B?")
leia(b)

c<-a
a<-b
b<-c

escreval(" o A vale: ", a)
escreval(" o B vale: ", b)



Fimalgoritmo