Algoritmo "repeticao2"

Var

i, valum, valdois, soma, media : real

Inicio

i <- 0

enquanto i <> -1 faca

escreva("Digite a 1 nota")
leia(valum)

escreva("Digite a 2 nota")
leia(valdois)

soma <- valum + valdois

media <- (valum + valdois)/2

escreval("Soma: ", soma)
escreval("Média: ", media)

escreval("digite -1 para parar")
leia(i)

escreval("### Próxima nota ###")

fimenquanto


Fimalgoritmo